### ISSUE TITLE
about pull request

### ISSUE THREAD

**Issue by zerlindali** [hejianjiao/BingWallpaper#4]
The first person to pull request whether need to pull the complete project including java file, jar and so on? Others pull request changes?

**Comment by JavaProgrammerLB** [comment]
@ligui989 
提交java的核心代码就可以了吧，其他的比如eclipse的配置文件，class文件或其他非核心代码的文件都设置为gitignore
提交的时候，提交以自己的名字或昵称命名的文件夹
这样操作如何？

**Comment by zerlindali** [comment]
No problem! Every programmer can create their own branch named their name or nickname, and then pull request the folder which also named their name or nickname.When programmers complete their code, merges into master branch. Is that ok?

**Comment by JavaProgrammerLB** [comment]
@ligui989 
I am agree with you!
