### ISSUE TITLE
有点儿小bug

### ISSUE THREAD

**Issue by q673230559** [hejianjiao/BingWallpaper#7]
liubei 的JavaBingWallpaper.java  80行似乎应该改成
BufferedImage image = ImageIO.read(new URL("http://www.bing.com/"+File.separator+url));

**Comment by q673230559** [comment]
@JavaProgrammerLB

**Comment by JavaProgrammerLB** [comment]
是的，问题存在
产生这个问题是因为原来的url的值是：
http://s.cn.bing.net/az/hprichbg/rb/WestBow_ZH-CN11767628474_1920x1080.jpg
现在的url的值是：
/az/hprichbg/rb/ColorfulTromso_ZH-CN9894938772_1920x1080.jpg
Bing修改了api

**Comment by q673230559** [comment]
是的 @JavaProgrammerLB

**Comment by Diego2048** [comment]
您好，我已收到您的邮件，谢谢
